#!/usr/bin/env bash
# build_wasm.sh - Compile the WASM application and embed it as a C header
#
# Prerequisites:
#   - wasi-sdk installed (https://github.com/WebAssembly/wasi-sdk/releases)
#   - xxd (part of vim-common on most distros)
#
# Usage:
#   export WASI_SDK=/opt/wasi-sdk   # or wherever you installed it
#   bash build_wasm.sh

set -euo pipefail

WASI_SDK="${WASI_SDK:-/opt/wasi-sdk}"
CLANG="${WASI_SDK}/bin/clang"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WASM_APP_DIR="${SCRIPT_DIR}/wasm_app"
OUTPUT_HEADER="${SCRIPT_DIR}/src/led_toggle_wasm.h"
WASM_OUT="${WASM_APP_DIR}/led_toggle.wasm"

echo "[1/3] Compiling led_toggle.c -> led_toggle.wasm"
"${CLANG}"                              \
    --target=wasm32-unknown-unknown     \
    -nostdlib                           \
    -Wl,--no-entry                      \
    -Wl,--export=app_main               \
    -Wl,--allow-undefined               \
    -O2 -g0                             \
    -o "${WASM_OUT}"                    \
    "${WASM_APP_DIR}/led_toggle.c"

echo "[2/3] Converting WASM binary to C header"
TMP=$(mktemp)
xxd -i "${WASM_OUT}" > "${TMP}"

# Extract array name and length generated by xxd, then wrap in our header
ARRAY=$(grep 'unsigned char' "${TMP}" | sed 's/unsigned char \([^ ]*\)\[\].*/\1/')
LENGTH=$(grep 'unsigned int' "${TMP}" | sed 's/.*= \([0-9]*\).*/\1/')

cat > "${OUTPUT_HEADER}" <<HEADER
/*
 * src/led_toggle_wasm.h  -- AUTO-GENERATED by build_wasm.sh, do not edit.
 *
 * Regenerate with:  bash build_wasm.sh
 */
#ifndef LED_TOGGLE_WASM_H
#define LED_TOGGLE_WASM_H
#include <stdint.h>

HEADER

# Paste the raw xxd output but rename to our expected symbols
sed "s/${ARRAY}/led_toggle_wasm/g" "${TMP}" | \
    sed 's/unsigned char/static const uint8_t/' | \
    sed 's/unsigned int/static const uint32_t/' | \
    sed 's/led_toggle_wasm_len/led_toggle_wasm_len/' \
    >> "${OUTPUT_HEADER}"

echo "" >> "${OUTPUT_HEADER}"
echo "#endif /* LED_TOGGLE_WASM_H */" >> "${OUTPUT_HEADER}"

rm -f "${TMP}"

echo "[3/3] Header written to ${OUTPUT_HEADER}"
echo "      WASM size: $(wc -c < "${WASM_OUT}") bytes"
echo "Done. Now run: west build -b nucleo_f446re ."
